// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihhdazltdyctyygxcblw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloaGRhemx0ZHljdHl5Z3hjYmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NDUwMzgsImV4cCI6MjA4ODQyMTAzOH0.9BOS9iES7lPjlPsy8Yyu2gb4kiqFG01nFMDMhFJdrSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});